### ISSUE TITLE
Create an executable using ocra on Windows

### ISSUE THREAD

**Issue by kojix2** [kojix2/LibUI#16]
I thought it would be easy to do, but it turns out it's not as easy as I thought.
I need to investigate how to make an executable using libui...

**Comment by a9xdev** [comment]
In order to build a exe with Ocra, it's important to include 3 DLLs from ruby_built_in_dlls folder:

libssp-0.dll, libgmp-10.dll and libffi-7.dll

`ocra app.rb --add-all-core --gem-all=fiddle --dll ruby_builtin_dlls/libssp-0.dll --dll ruby_builtin_dlls/libgmp-10.dll --dll ruby_builtin_dlls/libffi-7.dll --chdir-first --icon assets\app.ico --windows --verbose --output out\app.exe`

I've also included --gem-all=fiddle to ensure all of the Fiddle files are included.

**Comment by kojix2** [comment]
Amazing!
I have confirmed that I can use this command to create an application that runs on Windows. Thank you very much!
