### ISSUE TITLE
The Usage sample in README crashes when run in irb.

### ISSUE THREAD

**Issue by kojix2** [kojix2/LibUI#3]

**Comment by gemmaro** [comment]
I found a description of the timing of the parsing in "[Rurema](https://docs.ruby-lang.org/ja/latest/library/irb.html) > 使用上の制限 > ローカル変数の宣言". (It may be an overlook, but I could not find this in [the English documentation](https://docs.ruby-lang.org/en/master/).)

I used it as a reference and was able to get it to start successfully by enclosing [the entire code shown in Usage](https://github.com/kojix2/libui#usage) in `begin` to `end`.

However, there are still some concerns:
* irb method completion doesn't work because it is inside the `begin` block.
* It freezes when I press the close button of the window. (However, the window will disappear when irb is closed, so this is ok.)

## Environment and Version

```shell-session
$ uname -mprsv
Darwin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64 i386

$ ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]

$ irb -v
irb 1.3.0 (2020-12-25)
```

**Comment by kojix2** [comment]
Thank you very much. The problem has been fixed. 
The problem probably had something to do with garbage collection. 
See https://github.com/kojix2/LibUI/issues/8 for more details.

After resolving issue 8, the sample on the top page now works.
(It still freezes after pressing the close button though).
