### ISSUE TITLE
[Question / Documentation] Support on non-linux platforms?

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/libui#5]
Hey there kojix2 - you are the same guy who is also active at
ruby-gtk right? :) So great to see libui! Hopefully this can be 
useful as an additional platform (probably easier to get to
work than ruby-gtk for example).

Which brings me to my question - perhaps that question can
be answered in the main README so no need to answer
this here I suppose; README is great because more people
can read it.

Anyway - my question specifically is: how is the windows support
that is, libui working on windows? Can it work "natively" aka
without WSL? (I know that ruby + WSL works very well; I can
even use ruby-gtk on windows via WSL, but something 
native that is easier to install on windows would be GREAT.
I solve my personal needs on linux via the commandline,
but for elderly people, this would be great.)

Anyway, hopefully libui can remain active! I look forward to
some advanced styling via CSS too. :-) (Not sure if this
already works, I have not yet worked through the examples
so it will take me a while to get familiar with libui)

**Comment by kojix2** [comment]
Hi @rubyFeedback 

It's nice to see you again. And thanks for looking at the project. 

Of course libui supports Window. You do not need to use WSL. 
The gem package include three types of shared libraries: 
`libui.dll`, `libui.dylib`, and `libui.so`. 

These three files are only 1.4 MB in total. (You can further reduce 
the file size by deleting libui.dylib and `libui.so.  Because they are 
not used in Windows. libui.dll is only 275KB.)

So, just install the gem and it will work natively on Windows.

However, libui is not a general-purpose GUI library. 
It is not as expressive as a comprehensive library such as ruby-gtk3.
I don't think it is possible to implement advanced styling in CSS with libui.

Libui is good for creating small tools for Windows. 
Parhaps, It may be the best Ruby gem available today for this purpose. 
However, it is not suitable for writing complex GUIs with less lines
of Ruby-style code. It also does not support object-oriented widgets.
Of course, we could add an object-oriented widget class, like Python 
or Perl bindings, but I worry that it would be incomplete.

Anyway, I will continue to maintain it. 
If you find any problems, please report the issue or send me PR. 

Thank you.

**Comment by kojix2** [comment]
I Added screenshots to README to clarify support for Windows.
I close the issue. 

But, it might be worth considering releasing a Gem that contain only DLL file for Windows.
