### ISSUE TITLE
Button on-click event - simplified API proposal

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/LibUI#6]
Hey there kojix2. I hope it is ok to give more suggestions for change. :)

Currently we have to use the API like this for libui:

    button = UI.new_button('Button')
    UI.button_on_clicked(button) {

I believe we could shorten this a bit.

For example, this would be neater API-wise in my opinion:

    button = UI.new_button('Button')
    button.on_clicked {

In fact - I am actually doing this in my custom ruby-gtk "bindings".

My long-term dream would be to actually use a "unified"
API like this consistently for both ruby-gtk and libui. That
way I could write the "logic" just once, and then have it
work in ruby-gtk and libui and so forth. (I am ok omitting
features for libui, to keep it simple; just focusing on the
simple stuff, like buttons, text-entries and these things.)

(I understand that time is a limited resource and your
time is limited too - no worries. Just thinking about
this in the long term, say, 6 months to 12 months in
the future from now on.)

The advantage for:

    button.on_clicked {

Would be that the moment we have such a method, we can
alias it simply, so people can use whatever they want
to, such as:

    button.clicked {

By the way, libui reminds me a bit of ruby shoes from _why.
I think many ruby-users never heard about libui before; I
found it due to your post on ruby-reddit. Perhaps if you feel
libui becomes more stable, consider giving an update in the
middle of next year or something like this.

Anyway, this year is slowly closing, and I am slowly transitioning
into holidays (sort of), so, happy holidays to everyone! Not
sure how holidays are in japan, but ruby always has a xmas
release on 24th of december. :)

I'll probably do some more testing next year or so! Cheers. \o/

**Comment by kojix2** [comment]
Thank you for your suggestion.

I know what you are thinking and I agree to some extent.
But, to be honest, I don't want to do this right now...

The main reason is, that my understanding of libui is not good enough. 
I think that making bindings is like making a plastic model. 
In Ruby, it's easy because you can define methods dynamically. 
But, it takes time to understand the whole picture of libui 
and know what the authors thought when they created it.

The other concern is that increasing the code base
will make it more difficult to maintain.

If I get used to libui enough and feel that I can make something 
useful, I may add some object oriented features and 
try to add more Ruby-like syntax like you suggested...
But don't expect too much.

Even though it is Christmas, the city is quiet and the stars look 
more beautiful than in previous years. I do not know where on
 earth you are, but please take care of your health. 

Have a nice holiday!

**Comment by kojix2** [comment]
Reference projects:
 https://github.com/grkek/iu

**Comment by kojix2** [comment]
More than a year and a half has passed since my last comment.
When I started the LibUI project, I had the idea of creating a high-level API, but it did not happen. 
Currently, LibUI exists as a thin wrapper library for c-libui. And I am happy with it. I will continue to develop and maintain it.
