### ISSUE TITLE
Two things about libui-ng: one is a build failure with "rake"; the other is a suggestion

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/LibUI#63]
Hey there kojix2,

I tried to compile/install libui-ng via the rake command you show in the README.

Specifically:

    rake libui-ng:build[hash]

It yields this problem though:

    [Rake] Downloading libui-ng
    [Rake] Failed. 404 Not Found. Please check https://github.com/libui-ng/libui-ng/archive/hash.zip

Not sure why. Is the URL wrong or has it moved? It probably worked for you in the past
but right now it does not work for me.

There is another request, a small one.

Would it be possible to add code that allows us to distinguish whether we run the libui variant
or libui-ng?

Not sure about the API. Perhaps:

    LibUI::VERSION # if you want a generic constant as string

And it could return:

"libui"

or

"libui-ng"

As string.

This may be helpful when we may want to support both libui and
libui-ng, but check whether a specific functionality is available.
At the least if the ruby-libui gem supports both variants.

**Comment by kojix2** [comment]
Hi. 

Rake task can take arguments. [hash] means the commit hash. 
So execute the following command with no arguments.

```
rake libui-ng:build
```

You can use hash only to build libui-ng for a specific commit in the past.

```
rake libui-ng:build[b0d9d3b]
```

**Comment by kojix2** [comment]
> Would it be possible to add code that allows us to distinguish whether we run the libui variant
or libui-ng?

This feature will not be implemented. This is because v0.0.X supports libui and v0.1.X will support libui-ng. It is not intended to switch between libui and libui-ng. Currently there is a rake tasks to download shared libraries from andlabs/libui, but this will be removed in the future.

The shared libraries used by LibUI can be identified by the following code.

```ruby
require "libui"

LibUI.ffi_lib
# => "/home/kojix2/Ruby/LibUI/vendor/libui.so"
```

On linux, you can browse the contents of shared libraries with the nm command.

```
nm /home/kojix2/Ruby/LibUI/vendor/libui.so
```

Use `grep` to see if any libui-ng specific functions exist. If it exists, it is a shared library of libuii-ng.

```
nm /home/kojix2/Ruby/LibUI/vendor/libui.so | grep uiWindowResizeable
# 00000000000276e0 T uiWindowResizeable
```
