### ISSUE TITLE
Question: Why choose `fiddle` rather than `ffi`?

### ISSUE THREAD

**Issue by ccmywish** [kojix2/LibUI#70]
Hi @kojix2 

The `ffi` seems more idiomatic for Ruby, for example: 
```ruby
# ffi
attach_function :puts, [ :string ], :int

# fiddle
floor = Fiddle::Function.new(
          libm['floor'],
          [Fiddle::TYPE_DOUBLE],
          Fiddle::TYPE_DOUBLE
        )
```
As you can see, in `ffi` we write just symbols directly to represent C types.  

So, I suspect there might be some technical reasons for the use of `fiddle` rather than `ffi`. What are them?

**Comment by kojix2** [comment]
The reason for using Fiddle instead of Ruby-FFI for this project is not technical. It is because Ruby-FFI is a Ruby standard library and is expected to work on almost all environments where Ruby is installed. I think Ruby-FFI is better than Fiddle in the technical aspects.

libUI was created with school children in mind. Schools may not allow downloading or compiling of libraries. Ruby-FFI will only work if you can use libffi, compile C language extensions, and have an internet connection. Fiddle exchanging Ruby-FFI software with a friend on a USB stick would be easier. The idea of children programming in Ruby may sound strange today, but such a situation was possible in Japan until about 10 years ago.

In any case, Fiddle was chosen not because of technical reasons or my preference. It is because it works everywhere.

**Comment by kojix2** [comment]
Also, I personally prefer Ruby-FFI, but the above comparison is not fair:

```ruby
# FFI
attach_function :puts, [ :string ], :int

# Fiddle
extern "int puts(const char* s)"
```

**Comment by kojix2** [comment]
I am glad to hear of such attempts.

About 2 years ago, I copied some of my work to Gitee, in case I lost access to GitHub from China and we might not have access to Chinese repositories either, LibUI is one of them. So you can get the LibUI source code from there if you need it. It may be a bit out of date.

https://gitee.com/kojix/LibUI
