### ISSUE TITLE
Table example: 

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/LibUI#77]
Hello kojix2,

I took this example from your examples/ directory and modified it a tiny bit (just in case you wonder why it is not the same):

    require 'libui'

    alias e puts

    UI = LibUI

    LibUI.init

    main_window = LibUI.new_window('Animal sounds', 300, 200, 1)

    hbox = LibUI.new_horizontal_box
    LibUI.window_set_child(main_window, hbox)

    data = [
      %w( cat meow ),
      %w( dog woof ),
      %w( chicken cock-a-doodle-doo ),
      %w( horse neigh ),
      %w( cow moo )
    ]

    # Protects BlockCaller objects from garbage collection.
    @block_callers = []
    def rbcallback(*args, &block)
      args << [0] if args.size == 1 # Argument types are omitted
      block_caller = Fiddle::Closure::BlockCaller.new(*args, &block)
      @block_callers << block_caller
      block_caller
    end

    model_handler = UI::FFI::TableModelHandler.malloc
    model_handler.to_ptr.free = Fiddle::RUBY_FREE
    model_handler.NumColumns   = rbcallback(4) { 2 }
    model_handler.ColumnType   = rbcallback(4) { 0 }
    model_handler.NumRows      = rbcallback(4) { 5 }
    model_handler.CellValue    = rbcallback(1, [1, 1, 4, 4]) do |_, _, row, column|
      UI.new_table_value_string(data[row][column])
    end
    model_handler.SetCellValue = rbcallback(0, [0]) {}

    model = UI.new_table_model(model_handler)

    table_params = UI::FFI::TableParams.malloc
    table_params.to_ptr.free = Fiddle::RUBY_FREE
    table_params.Model = model
    table_params.RowBackgroundColorModelColumn = -1

    table = UI.new_table(table_params)
    LibUI.table_append_text_column(table, 'Animal', 0, -1)
    LibUI.table_append_text_column(table, 'Description', 1, -1)

    LibUI.box_append(hbox, table, 1)
    LibUI.control_show(main_window)

    LibUI.window_on_closing(main_window) {
      e 'Bye Bye'
      UI.quit
      1
    }

    UI.main
    UI.free_table_model(model)
    UI.uninit

Do you know if there is a way to obtain the currently selected row? If so could you add this information
to the table example? Perhaps by adding a button on the bottom, and on-click event of this button the
current selection could be shown, if that is possible.

Are there any other events or methods we can use on the table? It is still useful for showing tabulated
information, but I would love to know whether we can make tables more useful. I think Andy is doing
so via glimmer already (e. g. when he is updating and modifying the table data) but I wonder how this
can be done via raw LibUI without glimmer too, so I can understand what is going on.

Thanks for your time investment here in general by the way.

**Comment by AndyObtiva** [comment]
You’re not supposed to worry about what is going on behind the scenes though yet focus instead on solving the business problems at a higher level and accomplishing high level user goals. You’re doing it all wrong if you worry yourself about low level details instead of the high level problems to solve. Also, you could have just dug into Glimmer DSL for LibUI code to figure out table selection, which is a new feature that got added recently. You could go back in commits to find the one that includes table selection implementation code.

**Comment by kojix2** [comment]
I've been using GitHub for ten years now, and I've come to realize that the motivations for programming are surprisingly diverse. For some people, building a personal pyramid in the garden of their mind might be more important than solving business or user problems. (I might be one of them, actually.) 
By the way, the recently added `uiTableOnRowClicked` might be just what you're looking for.

https://github.com/libui-ng/libui-ng/blob/2746470ed8bae73588013f176b37baf32af42618/ui.h#L3798-L3813

**Comment by AndyObtiva** [comment]
Right, but in this case, I believe @rubyFeedback is just distracted for the wrong reasons just as he often was in past issue requests. He could have easily found the answers for himself by searching for [table selection in Glimmer DSL for LibUI's README](https://github.com/AndyObtiva/glimmer-dsl-libui#table-api) and he could have looked at Glimmer's code for examples of using table selection in the LibUI Ruby binding. So, although on the surface, this seems like a legitimate request, it is actually just a distraction and the result of lack of effort (not a genuine intent to learn). 

Also, regardless of diversity of motivations on GitHub, all motivations are ultimately about serving user needs, including personal needs (like learning), because users use software. So, serving user needs is always the right goal to keep in mind in Software Engineering. And, being distracted from that goal leads to doing a poor job and wasting time. The best Software Engineers are always the ones that learn how to delegate work to libraries by trusting them. The ones who do not know how to do that usually do not write good code at work because they worry too much about low-level details and micromanagement instead of trusting libraries like Glimmer and Rails through delegation to do a good job and focus on high level user needs instead.

In any case, these are the methods that handle table selection in the LibUI Ruby binding (but I think it's a waste of time to worry about how they work instead of simply just building something with Glimmer DSL for LibUI and experimenting with Glimmer syntax instead as that's a much better investment):
- LibUI.table_get_selection
- LibUI.table_get_selection_mode
- LibUI.table_on_row_clicked
- LibUI.table_on_row_double_clicked
- LibUI.table_on_selection_changed
- LibUI.table_set_selection
- LibUI.table_set_selection_mode

Of course, table selection is much simpler in Glimmer DSL for LibUI due to automating a lot of the work and due to table selection data-binding support in one line as demonstrated in [Basic Table Selection](https://github.com/AndyObtiva/glimmer-dsl-libui/blob/master/docs/examples/GLIMMER-DSL-LIBUI-BASIC-EXAMPLES.md#basic-table-selection).

**Comment by kojix2** [comment]
Thanks Andy, Glimmer makes it easy to create desktop applications. I think this is really great. I appreciate it.

> On the RubyGems server, there are hidden [gems](https://rubygems.org/profiles/shevy), known only to their creator, much like secret ancient ruins in the jungle. At first glance, they may seem old, but they are special, made with love and effort. They are like ancient cities that were once magnificent but are now gone. Humans are similar, sometimes struck by sudden misfortunes that ruin everything. But their passion continues to burn.

This is a fairy tale I thought of, so maybe it's not true. The internet has many mysteries. In real life, I agree with Andy...
